spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: jdbc:mysql://localhost:3306/parqueadero?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8087
  servlet:
    context-path: /estacionamiento
